name: 02 Build Tailwind

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-tailwind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build

      - name: Upload generated CSS
        uses: actions/upload-artifact@v4
        with:
          name: tailwind-output
          path: src/app/static/css/output.css
